language: java
jdk:
  - openjdk10
  - openjdk11
os:
  - linux
dist:
  - trusty
  - precise
jobs:
  include:
    - stage: Test
      script: ./mvnw clean test
notifications:
  email: tphuoc1998@gmail.com